---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yky.
--- DateTime: 2021/8/9 21:37
---

local la = {}
-- metatable的名字无所谓
local metaa = {}

function la.new(x, y, z)
    local v = {x = x, y = y, z = z}
    -- 把vector3d这个变量和meta联系起来了
    setmetatable(v, metaa)
    return v
end

function addition(v1, v2)
    setmetatable(la, metaa)
    return v1
end

print(getmetatable(la.new(1,2,3), 0))

-----------------------------------------------
local lb = 2
local metab = {}
-- 这里报错，因为设置metatable的第一个参数必须得是一个table
setmetatable(lb, metab)
print(getmetatable(lb))