---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yky.
--- DateTime: 2021/6/26 16:01
---
print("hello world")

score = 0
str1 = "haha"

print(type(score))
print(type(str1))

-- .. 的作用类似于其他变成语言的 +
house = "house"
print("this is my ".. house)

-- 除法 //, 5.1的lua版本没有双斜杠这个运算符，所以可以用math.floor 或者 math.ceil
val1 = 10
val2 = 3
print(val1 // val2)
print(math.floor(val1/val2))
print(math.ceil(val1/val2))

-- lua的条件判断，关键词 then，end
-- elseif 是连在一起，分开会让lua以为是连续的两个if，每一个if，不管是if还是elseif，后面都需要跟一个then
if val2 == val1 - 7  then
    print("yes")
elseif val2 ~= val1 then
    print("no")
end

-- 逻辑运算符 and or not
if val1 > 0 and val2 > 0 then
    print("都大于0")
end

val3 = -5
if val1 > 0 or val3 > 0 then
    print("其中一个大于0")
end

-- string 函数
-- 替换 string.gsub(str，oldCharacter, newCharacter)
-- 截取 string.sub(str, index1, index2)，闭区间
-- 长度 string.len(str) 语法糖 #str
-- 查找 string.find(str, target)
str = "123456798"
print(string.sub(str, 1,2))
-- 这里明明返回的是一个num
print(type(string.find(str, "1")))
-- 但是if判断语句居然成功了
if string.find(str, "1") then
    print("yep")
end

-- multi-line string，如果像下面这样写多行string会报错
--str2 = " 123
--13213135"
-- 应该用中括号
str3 = [[6
sdfsdfsdfsdsd
sdfsdffsdfsdf]]

print(str3)

-- multi-assign 多变量声明，快速交换两个变量的值
x, y = 1, 2
x, y = y, x
print("x:"..x..", y:"..y)

-- 常用的函数
print(os.date())
-- print(os.difftime())
print(os.time())

-- 循环
for i = 1, 10 do
    print(i)
end

-- 也有类似go的循环
--for i, v in ipairs() do
--
--end

count = 1
while count < 5 do
    print("count:"..count)
    count = count +1
end


-- 变量的范围，在lua中，好像没有局部变量的概念，一个变量在任何地方被声明后，在后面的语句中好像都可以调用
for i = 1, 10 do
    tempInner = i
end
print("tempInner:" ..tempInner)
-- 如果想要变成局部变量，那么需要
for i = 1, 10 do
    local tempInner2 = i
end
-- 这条语句会报错
-- print("tempInner:" ..tempInner2)

-- lua的标准输入
putIn = io.read("*n")
print(putIn)